app/customer/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed

from wtforms import StringField, PasswordField, SelectField, TextAreaField
from wtforms.validators import DataRequired, Length, EqualTo

from app.models import Category

allowed_exts = ['pdf', 'docx', 'png', 'jpg', 'jpeg', 'gif']

class TicketForm(FlaskForm):
	subject = StringField('Subject',
		validators=[DataRequired(), Length(min=4, max=128)])
	category = SelectField('Category',
		validators=[DataRequired()])
	body = TextAreaField('Message',
		validators=[DataRequired()])
	attachment = FileField('Attachment',
		validators=[FileAllowed(allowed_exts, 'This file extension is not allowed')])

	def __init__(self, *args, **kwargs):
		super(TicketForm, self).__init__(*args, **kwargs)
		self.category.choices = [('', '-- Please select category --')]+[(category.id, category.category) for category in Category.query.all()]

class UpdateTicketForm(FlaskForm):
	category = SelectField('Category',
		validators=[DataRequired()])

	def __init__(self, *args, **kwargs):
		super(UpdateTicketForm, self).__init__(*args, **kwargs)
		self.category.choices = [('', '-- Please select category --')]+[(category.id, category.category)
			for category in Category.query.all()]

class CommentForm(FlaskForm):
	comment = TextAreaField('Comment',
		validators=[DataRequired()])

class ChangeProfileForm(FlaskForm):
	profile = FileField('Change Profile',
		validators=[FileRequired(), FileAllowed(['png', 'jpg', 'jpeg'], 'This file extension is not allowed')])

class ChangePasswordForm(FlaskForm):
	password = PasswordField('New Password',
		validators=[DataRequired(), Length(min=6, max=32)])
	confirm_password = PasswordField('Confirm Password',
		validators=[DataRequired(), EqualTo('password')])

app/customer/views.py
from flask import Blueprint, current_app, render_template as _render, send_file, redirect, request, url_for, flash
from flask_login import current_user

from app.customer.forms import TicketForm, UpdateTicketForm, CommentForm, ChangeProfileForm, ChangePasswordForm
from app.models import User, Ticket, Comment, Notification

from app.utils.generate_digits import random_numbers
from app.utils.authorized_role import login_required
from app.exts import db

from werkzeug.utils import secure_filename

from sqlalchemy import desc

from werkzeug.security import generate_password_hash

import datetime
import uuid
import os

customer_blueprint = Blueprint('customer', __name__)
path = os.getcwd()

# Pass variable to all templates
def render_template(*args, **kwargs):
	notifications = Notification.query.filter(Notification.receiver_id==current_user.id).filter(Notification.seen==False).order_by(desc(Notification.created_at)).all()
	year = datetime.date.today().year
	return _render(*args, **kwargs, notifications=notifications, year=year)

@customer_blueprint.route('/dashboard')
@login_required(role='Customer')
def dashboard():
	id = current_user.id
	open = Ticket.query.filter_by(author_id=id).filter_by(status_id=1).all()
	solved = Ticket.query.filter_by(author_id=id).filter_by(status_id=2).all()
	pending = Ticket.query.filter_by(author_id=id).filter_by(status_id=3).all()
	closed = Ticket.query.filter_by(author_id=id).filter_by(status_id=4).all()
	
	return render_template('customer/dashboard.html', open=open, solved=solved, pending=pending, closed=closed)

@customer_blueprint.route('/my-tickets', methods=['GET'])
@login_required(role='Customer')
def my_tickets():
	tickets = Ticket.query.filter(Ticket.author_id==current_user.id).order_by(desc(Ticket.created_at)).all()
	form = TicketForm()
	return render_template('customer/my_tickets.html', form=form, tickets=tickets)

@customer_blueprint.route('/create-ticket', methods=['GET', 'POST'])
@login_required(role='Customer')
def create_ticket():
	form = TicketForm()
	if form.validate_on_submit():
		number = random_numbers()
		priority = 1 # Low priority
		status = 1 # Open status

		id = current_user.id
		file = form.attachment.data
		if file is not None:
			FOLDER_ID = os.path.join(path, 'app/static/uploads/attachments/' + str(id))
			# Recursively create the paths, if the preceding path doesn't exist
			if not os.path.exists(FOLDER_ID):
				os.makedirs(FOLDER_ID)

			original_f = file.filename
			# Rename the uploaded file
			filename, ext = os.path.splitext(original_f)
			filename = uuid.uuid4().hex
			attachment = secure_filename(str(filename + ext))
			# then save it to the designated folder
			file.save(os.path.join(FOLDER_ID, attachment))
		else:
			attachment = None
			original_f = None

		ticket = Ticket(number=number, subject=form.subject.data, body=form.body.data, author_id=current_user.id, owner_id=None, category_id=int(form.category.data), priority_id=priority, status_id=status, orig_file=original_f, file_link=attachment)
		
		db.session.add(ticket)
		db.session.commit()
		flash('Ticket has been created.', 'primary')
		return redirect(url_for('customer.my_tickets'))

@customer_blueprint.route('/view-ticket/<int:id>', methods=['GET', 'POST'])
@login_required(role='Customer')
def view_ticket(id):
	ticket = Ticket.query.filter(Ticket.author_id==current_user.id).filter_by(id=id).first()
	comments = Comment.query.filter(Comment.ticket_id==id).all()
	
	if not ticket:
		return redirect(url_for('customer.my_tickets'))
	
	form = UpdateTicketForm(category=ticket.category_id)
	comment_form = CommentForm()
	if form.validate_on_submit():
		if ticket.category_id != int(form.category.data) and ticket.owner_id is not None:
			Notification.send_notification(message='updated category on ticket', receiver_id=ticket.owner_id, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
		ticket.category_id = form.category.data

		db.session.commit()
		flash('Ticket has been updated.', 'primary')
		return redirect(url_for('customer.view_ticket', id=id))
	return render_template('customer/view_ticket.html', form=form, comment_form=comment_form, ticket=ticket, comments=comments)

@customer_blueprint.route('/comment-ticket/<int:id>', methods=['GET', 'POST'])
@login_required(role='Customer')
def comment_ticket(id):
	ticket_id = Ticket.query.get_or_404(id)
	comment_form = CommentForm()
	if comment_form.validate_on_submit():
		author_id = ticket_id.author_id
		owner_id = ticket_id.owner_id
		comment = comment_form.comment.data

		message = 'commented on ticket'
		# Send notification to the owner, if the ticket is mine and is not assigned to me
		if author_id == current_user.id and owner_id != current_user.id and owner_id is not None:
			Notification.send_notification(message=message, receiver_id=owner_id, sender_id=current_user.id, ticket_id=ticket_id.id, seen=False)

		db.session.add(Comment(comment=comment, author_id=current_user.id, ticket_id=ticket_id.id))
		db.session.commit()
		flash('Your comment has been posted.', 'primary')
		return redirect(url_for('customer.view_ticket', id=id))
	return render_template('customer/view_ticket.html', comment_form=comment_form)

@customer_blueprint.route('/ticket/delete/<int:uid>/<int:tid>', methods=['GET', 'POST'])
@login_required(role='Customer')
def delete_ticket(uid, tid):
	ticket_id = Ticket.query.get_or_404(tid)
	if request.method == 'POST':
		if ticket_id.file_link:
			FOLDER_ID = os.path.join(path, 'app/static/uploads/attachments/' + str(uid))
			os.remove(os.path.join(FOLDER_ID, ticket_id.file_link))

		db.session.delete(ticket_id)
		db.session.commit()
		flash('Ticket has been deleted.', 'primary')
		return redirect(url_for('customer.my_tickets'))
	return redirect(url_for('customer.view_ticket', id=tid))

@customer_blueprint.route('/download/attachment/<int:id>/<filename>')
def download_attachment(id, filename):
	FOLDER_ID = os.path.join(path, 'app/static/uploads/attachments/' + str(id))
	location = os.path.join(FOLDER_ID, filename)
	return send_file(location, as_attachment=True)

@customer_blueprint.route('/my-profile', methods=['GET', 'POST'])
@login_required(role='Customer')
def my_profile():
	user = User.query.filter(User.id==current_user.id).first()
	form = ChangeProfileForm()
	if form.validate_on_submit():
		file = form.profile.data
		# Rename the uploaded file
		filename, ext = os.path.splitext(file.filename)
		filename = str(user.id)
		profile = secure_filename(filename + ext)
		# then save it to the designated folder
		file.save(os.path.join(current_app.config['PROFILE_DIR'], profile))

		user.image = profile
		db.session.commit()
		flash('Your profile has been changed.', 'primary')
		return redirect(url_for('customer.my_profile'))
	return render_template('customer/my_profile.html', form=form, user=user)

@customer_blueprint.route('/change-password', methods=['GET', 'POST'])
@login_required(role='Customer')
def change_password():
	user = User.query.filter(User.id==current_user.id).first()
	form = ChangePasswordForm()
	if form.validate_on_submit():
		hashed_password = generate_password_hash(form.password.data)
		user.password = hashed_password
		db.session.commit()
		flash('Your password has been changed.', 'primary')
		return redirect(url_for('customer.change_password'))
	return render_template('customer/change_password.html', form=form)

@customer_blueprint.route('/notifications', methods=['GET'])
@login_required(role='Customer')
def notifications():
	my_notifications = Notification.query.filter(Notification.receiver_id==current_user.id).order_by(desc(Notification.created_at)).all()
	return render_template('customer/notifications.html', my_notifications=my_notifications)

@customer_blueprint.route('/read-notification/<int:tid>/<int:nid>', methods=['GET'])
@login_required(role='Customer')
def read_notification(tid, nid):
	ticket_id = Ticket.query.get_or_404(tid)
	notification_id = Notification.query.get_or_404(nid)
	
	notification_id.seen = True
	db.session.commit()
	return redirect(url_for('customer.view_ticket', id=ticket_id.id))

app/templates/customer/change_password.html
{% from 'macros/render_input.html' import render_input %}

{% extends 'layouts/dashboard.base.html' %}
{% block header %}
    {% block title %}Change Password{% endblock %}
{% endblock %}
{% block text %}
    Make sure your password is strong and easy to remember.
{% endblock %}
{% block content %}

<div class="max-w-1000">
    {% include 'includes/alert.html' %}
</div>

<!-- Change Password Form -->
<div class="content-box mb-3 content-lighten max-w-1000">
    <form action="#" method="POST" class="form-validation max-w-800" novalidate="">
        {{ form.csrf_token }}
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="password">New Password</label>
                    {{ render_input(form.password, "", "Password must be 6 to 32 characters long", **{"data-eye": ""}) }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="confirm_password">Confirm Password</label>
                    {{ render_input(form.confirm_password, "", "Confirm password is required", **{"data-eye": ""}) }}
                </div>
            </div>
        </div>
        <button type="submit" id="submit" class="btn btn-primary">Change Password</button>
    </form>
</div>

{% endblock %}
{% block script %}
{{ super() }}
<!--
<script>
    $('#submit').click(function(e) {
        e.preventDefault();
        alert('This functionality is not available for the demo.');
    });
</script>
-->
{% endblock %}

app/templates/customer/dashboard.html
{% extends 'layouts/dashboard.base.html' %}
{% block header %}
    {% block title %}Dashboard{% endblock %}
{% endblock %}
{% block content %}

<div class="max-w-1000">
    <div class="row">
        <div class="col-md-4 col-xl-3">
            <div class="card bg-clr-blue order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Open</h6>
                    <h2 class="text-right">
                        <i class="fa fa-envelope-open f-left"></i>
                        <span>{{ open|length }}</span>
                    </h2>
                    <p class="m-b-0">Total open tickets</p>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-xl-3">
            <div class="card bg-clr-green order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Solved</h6>
                    <h2 class="text-right">
                        <i class="fa fa-thumbs-up f-left"></i>
                        <span>{{ solved|length }}</span>
                    </h2>
                    <p class="m-b-0">Total solved tickets</p>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-xl-3">
            <div class="card bg-clr-yellow order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Pending</h6>
                    <h2 class="text-right">
                        <i class="fa fa-hourglass-end f-left"></i>
                        <span>{{ pending|length }}</span>
                    </h2>
                    <p class="m-b-0">Total pending tickets</p>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-xl-3">
            <div class="card bg-clr-pink order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Closed</h6>
                    <h2 class="text-right">
                        <i class="fa fa-envelope f-left"></i>
                        <span>{{ closed|length }}</span>
                    </h2>
                    <p class="m-b-0">Total closed tickets</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/customer/my_tickets.html
{% from 'macros/render_input.html' import render_input %}
{% from 'macros/render_select.html' import render_select %}
{% from 'macros/render_upload.html' import render_upload %}

{% extends 'layouts/dashboard.base.html' %}
{% block style %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/bootstrap-table/bootstrap-table.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/froala-editor/css/froala_editor.pkgd.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/froala-editor/css/froala_style.min.css') }}">
{% endblock %}

{% block header %}
    {% block title %}My Tickets{% endblock %}
{% endblock %}
{% block text %}
    List of all the tickets you've created.
{% endblock %}

{% block button %}
    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#createModal">
        Create New
    </button>
{% endblock %}
{% block content %}

<div class="max-w-1000">
    {% include 'includes/alert.html' %}
</div>

<div class="content-box mb-3 content-lighten max-w-1000">
    <table
        id="ticketTable"
        class="table table-striped table-responsive-sm"
        
        data-toggle="table"
        data-search="true"
        
        data-pagination="true"
        data-page-list="[10, 25, 50, 75]"
        
        data-show-columns="true"
        data-show-toggle="true"
        data-search-highlight="true"

        data-filter-control="true"
        data-buttons-class="dark"
        >
        <thead>
            <tr class="tr-class-1">
                <th data-field="number" rowspan="2" data-valign="middle" data-halign="center">ID</th>
                <th colspan="4">Ticket information</th>
            </tr>
            <tr class="tr-class-2">
                <th data-field="subject" data-valign="middle">Subject</th>
                <th data-field="author" data-valign="middle" data-width="150">Author name</th>
                <th data-field="priority" data-filter-control="select" data-card-visible="false">
                    Priority
                </th>
                <th data-field="status" data-filter-control="select" data-card-visible="false">
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            {% for row in tickets %}
            <tr id="tr-id-{{ row.id }}" class="tr-class-{{ row.id }}" data-title="{{ row.number }}" data-object='{"key": "value"}'>
                <td id="td-id-{{ row.id }}" class="td-class-{{ row.id }}" data-title="{{ row.number }}">
                    <a href="{{ url_for('customer.view_ticket', id=row.id) }}">{{ row.number }}</a>
                </td>
                <td>
                    {% if row.subject|length > 64 %}
                        {{ row.subject[:64-3] + '...' }}
                    {% else %}
                        {{ row.subject }}
                    {% endif %}
                </td>
                <td>{{ row.author.name }}</td>
                <td>{{ row.priority.priority }}</td>
                <td>{{ row.status.status }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createModalLabel">Create New</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('customer.create_ticket') }}" method="POST" enctype="multipart/form-data">
                    {{ form.csrf_token }}
                    <div class="form-group">
                        {{ render_input(form.subject, "Subject", "Subject is required") }}
                    </div>
                    <div class="form-group">
                        {{ render_select(form.category, "Category is required") }}
                    </div>
                    <div class="form-group">
                        {{ render_input(form.body, "Write a message...", "Message is required", rows="5") }}
                    </div>
                    <div class="mb-3">
                        <small class="text-muted">Only files with the following extensions will be allowed (PDF, DOCX, JPEG, JPG, PNG, GIF) and a maximun file size of 4 MB.</small>
                    </div>
                    <div class="input-group mb-3">
                        <div class="custom-file">
                            {{ render_upload(form.attachment) }}
                            <label class="custom-file-label" for="attachment">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text" id="">Upload</span>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block script %}
{{ super() }}
<!--
<script>
    $('#attachment').click(function() {
        $('#attachment').prop('disabled', true);
        alert('This functionality is not available for the demo.');
    });
</script>
-->
<script src="{{ url_for('static', filename='vendor/bootstrap-table/bootstrap-table.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/bootstrap-table/extensions/filter-control/bootstrap-table-filter-control.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/froala-editor/js/froala_editor.pkgd.min.js') }}"></script>
<script>
    $(document).ready(function() {
        new FroalaEditor('textarea#body', {
            toolbarButtons: ['fontFamily', '|', 'bold', 'italic', 'underline', 'undo', 'redo', 'codeView'],
            fontFamilySelection: true,
            pluginsEnabled: ['fontFamily']
        });

        $('#attachment').on('change', function() {
            var fileName = $(this).val();
            $(this).next('.custom-file-label').html(fileName);
        });

        $('#ticketTable').bootstrapTable();

        maxFileSize = 4 * 1024 * 1024
        $('#attachment').change(function() {
            // File size validation
            fileSize = this.files[0].size;
            if(fileSize > maxFileSize) {
                this.setCustomValidity('Maximum file size exceeded');
                this.reportValidity();
            }
            // File extension validation
            var ext = $(this).val().split('.').pop().toLowerCase();
            if($.inArray(ext, ['pdf', 'docx', 'png', 'jpg', 'jpeg', 'gif']) == -1) {
                alert('This file extension is not allowed');
            }
        });
    });
</script>
{% endblock %}

app/templates/customer/notifications.html
{% extends 'layouts/dashboard.base.html' %}
{% block style %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/datatables/css/datatables.bootstrap4.min.css') }}">
{% endblock %}

{% block header %}
    {% block title %}Notifications{% endblock %}
{% endblock %}
{% block text %}
    See who has left comments on your ticket, updated it, or assigned it.
{% endblock %}
{% block content %}

<!-- Notification Table -->
<div class="content-box mb-3 content-lighten max-w-1000">
    <table id="notificationTable" class="table table-striped table-borderless table-responsive-sm">
        <thead>
            <tr>
                <th>Notification</th>
                <th>Date Created</th>
            </tr>
        </thead>
        <tbody>
            {% for row in my_notifications %}
            <tr>
                <td>
                    {% if row.seen == 0 %}
                        <span class="indicator mr-1"></span>
                    {% endif %}
                    {% if row.sender.id == current_user.id %}
                        [You] {{ row.sender.name }}
                    {% else %}
                        {{ row.sender.name }}
                    {% endif %}
                    {{ row.message }}
                    <a href="{{ url_for('customer.read_notification', tid=row.ticket_notification.id, nid=row.id) }}">
                        #{{ row.ticket_notification.number }}
                    </a>
                </td>
                <td>{{ row.created_at.strftime('%m-%d-%Y, %H:%M') }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}
{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='vendor/datatables/js/jquery.datatables.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/datatables/js/datatables.bootstrap4.min.js') }}"></script>
<script>
    $(document).ready(function() {
        $('#notificationTable').DataTable({'ordering': false});
    });
</script>
{% endblock %}

app/templates/customer/view_ticket.html
{% from 'macros/render_input.html' import render_input %}
{% from 'macros/render_select.html' import render_select %}

{% extends 'layouts/dashboard.base.html' %}
{% block style %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/froala-editor/css/froala_editor.pkgd.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/froala-editor/css/froala_style.min.css') }}">
{% endblock %}

{% block header %}
    {% block title %}Ticket Information{% endblock %}
{% endblock %}
{% block text %}
    Our support team will handle this ticket, please wait for a while.
{% endblock %}

{% block button %}
    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal">
        Delete
    </button>
{% endblock %}
{% block content %}

<div class="max-w-1000">
    {% include 'includes/alert.html' %}
</div>

<!-- Ticket Info -->
<div class="content-box mb-3 content-lighten max-w-1000">
    <table class="table table-striped table-borderless">
        <tbody>
            <form action="{{ url_for('customer.view_ticket', id=ticket.id) }}" method="POST">
                {{ form.csrf_token }}
                <tr>
                    <td>Date Created</td>
                    <td>{{ ticket.created_at.strftime('%d %b %Y, %H:%M %p') }}</td>
                </tr>
                <tr>
                    <td class="w-25">Number</td>
                    <td>{{ ticket.number }}</td>
                </tr>
                <tr>
                    <td>Author</td>
                    <td>{{ ticket.author.name }}</td>
                </tr>
                <tr>
                    <td>E-mail address</td>
                    <td>
                        <a href="mailto:{{ ticket.author.email }}">{{ ticket.author.email }}</a>
                    </td>
                </tr>
                <tr>
                    <td>Subject</td>
                    <td>{{ ticket.subject }}</td>
                </tr>
                <tr>
                    <td>Body</td>
                    <td>
                        <div class="fr-view">{{ ticket.body|safe }}</div>
                    </td>
                </tr>
                <tr>
                    <td>Assignee</td>
                    <td>{{ ticket.owner.name }}</td>
                </tr>
                <tr>
                    <td>Category</td>
                    <td>
                        <div class="form-group row">
                            <div class="col-md-5">
                                {{ render_select(form.category, "Category is required") }}
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Priority</td>
                    <td>{{ ticket.priority.priority }}</td>
                </tr>
                <tr>
                    <td>Status</td>
                    <td>{{ ticket.status.status }}</td>
                </tr>
                <tr>
                    <td>Attachment</td>
                    <td>
                        {% if ticket.file_link %}
                        <a href="{{ url_for('customer.download_attachment', id=ticket.author.id, filename=ticket.file_link) }}">
                            {{ ticket.orig_file }}
                        </a>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <button type="submit" class="btn btn-primary btn-sm">Update</button>
                        <a href="{{ url_for('customer.my_tickets') }}" class="btn btn-secondary btn-sm">
                            Back
                        </a>
                    </td>
                </tr>
            </form>
        </tbody>
    </table>
</div>

<!-- Comment Section -->
<div class="content-box mb-3 content-lighten max-w-1000">
    <div class="comment-wrapper">
        {% if ticket.status.status != 'Closed' %}
        <form action="{{ url_for('customer.comment_ticket', id=ticket.id) }}" method="POST">
            {{ comment_form.csrf_token }}
            <div class="form-group">
                {{ render_input(comment_form.comment, "Write a message...", "Message is required", rows="5") }}
            </div>
            <button type="submit" class="btn btn-primary btn-sm pull-right">Post</button>
        </form>
        {% else %}
        <div class="text-center">
            <p>This ticket has been closed.</p>
        </div>
        {% endif %}
        
        <div class="clearfix"></div>
        <hr>
        
        {% for comment in comments %}
        <ul class="media-list">
            <li class="media">
                <a href="javascript:void(0)" class="pull-left mt-3 mr-3">
                    <img src="{{ url_for('static', filename='uploads/profiles/' + comment.user.image) }}" alt="profile-img" class="rounded">
                </a>
                <div class="media-body">
                    <span class="text-muted pull-right">
                        <small class="text-muted">{{ comment.created_at.strftime('%d %b %Y, %H:%M %p') }}</small>
                    </span>
                    <strong class="text-dark">{{ comment.user.name }}</strong>
                    <small class="text-muted">{{ comment.user.role }}</small>
                    <p>
                        <div class="fr-view">{{ comment.comment|safe }}</div>
                    </p>
                </div>
            </li>
        </ul>
        {% endfor %}
    </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this ticket? This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('customer.delete_ticket', uid=ticket.author.id, tid=ticket.id) }}" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='vendor/froala-editor/js/froala_editor.pkgd.min.js') }}"></script>
<script>
    $(document).ready(function() {
        new FroalaEditor('textarea#comment', {
            toolbarButtons: ['fontFamily', '|', 'bold', 'italic', 'underline', 'undo', 'redo', 'codeView'],
            fontFamilySelection: true,
            pluginsEnabled: ['fontFamily']
        });
    });
</script>
{% endblock %}