app/admin/views.py
from flask import Blueprint, current_app, render_template as _render, send_file, redirect, request, url_for, flash
from flask_login import current_user

from app.admin.forms import TicketForm, UpdateTicketForm, CommentForm, CategoryForm, PriorityForm, UserForm, UpdateRoleForm, ChangeProfileForm, ChangePasswordForm
from app.models import User, Ticket, Category, Priority, Status, Comment, Notification

from app.utils.generate_digits import random_numbers
from app.utils.authorized_role import login_required
from app.exts import db

from werkzeug.utils import secure_filename

from sqlalchemy import desc
from sqlalchemy import or_

from werkzeug.security import generate_password_hash

import datetime
import shutil
import uuid
import os

admin_blueprint = Blueprint('admin', __name__)
path = os.getcwd()

# Pass variable to all templates
def render_template(*args, **kwargs):
	notifications = Notification.query.filter(Notification.receiver_id==current_user.id).filter(Notification.seen==False).order_by(desc(Notification.created_at)).all()
	year = datetime.date.today().year
	return _render(*args, **kwargs, notifications=notifications, year=year)

@admin_blueprint.route('/dashboard')
@login_required(role='Administrator')
def dashboard():
	id = current_user.id
	open = Ticket.query.filter(or_(Ticket.author_id==id, Ticket.owner_id==id)).filter_by(status_id=1).all()
	solved = Ticket.query.filter(or_(Ticket.author_id==id, Ticket.owner_id==id)).filter_by(status_id=2).all()
	pending = Ticket.query.filter(or_(Ticket.author_id==id, Ticket.owner_id==id)).filter_by(status_id=3).all()
	closed = Ticket.query.filter(or_(Ticket.author_id==id, Ticket.owner_id==id)).filter_by(status_id=4).all()
	
	return render_template('admin/dashboard.html', open=open, solved=solved, pending=pending, closed=closed)

@admin_blueprint.route('/my-tickets', methods=['GET'])
@login_required(role='Administrator')
def my_tickets():
	tickets = Ticket.query.filter(or_(Ticket.author_id==current_user.id, Ticket.owner_id==current_user.id)).order_by(desc(Ticket.created_at)).all()
	form = TicketForm()
	return render_template('admin/my_tickets.html', form=form, tickets=tickets)

@admin_blueprint.route('/new-tickets', methods=['GET'])
@login_required(role='Administrator')
def new_tickets():
	tickets = Ticket.query.order_by(desc(Ticket.created_at)).all()
	form = TicketForm()
	return render_template('admin/new_tickets.html', form=form, tickets=tickets)

@admin_blueprint.route('/create-ticket', methods=['GET', 'POST'])
@login_required(role='Administrator')
def create_ticket():
	form = TicketForm()
	if form.validate_on_submit():
		number = random_numbers()
		priority = 1 # Low priority
		status = 1 # Open status

		id = current_user.id
		file = form.attachment.data
		if file is not None:
			FOLDER_ID = os.path.join(path, 'app/static/uploads/attachments/' + str(id))
			# Recursively create the paths, if the preceding path doesn't exist
			if not os.path.exists(FOLDER_ID):
				os.makedirs(FOLDER_ID)

			original_f = file.filename
			# Rename the uploaded file
			filename, ext = os.path.splitext(original_f)
			filename = uuid.uuid4().hex
			attachment = secure_filename(str(filename + ext))
			# then save it to the designated folder
			file.save(os.path.join(FOLDER_ID, attachment))
		else:
			attachment = None
			original_f = None

		ticket = Ticket(number=number, subject=form.subject.data, body=form.body.data, author_id=current_user.id, owner_id=None, category_id=int(form.category.data), priority_id=priority, status_id=status, orig_file=original_f, file_link=attachment)
		
		db.session.add(ticket)
		db.session.commit()
		flash('Ticket has been created.', 'primary')
		return redirect(url_for('admin.new_tickets'))

@admin_blueprint.route('/view-ticket/<int:id>', methods=['GET', 'POST'])
@login_required(role='Administrator')
def view_ticket(id):
	ticket = Ticket.query.filter_by(id=id).first()
	comments = Comment.query.filter(Comment.ticket_id==id).all()
	
	if not ticket:
		return redirect(url_for('admin.new_tickets'))
	
	form = UpdateTicketForm(owner=ticket.owner_id, priority=ticket.priority_id, status=ticket.status_id)
	comment_form = CommentForm()
	if form.validate_on_submit():
		if not form.owner.data:
			if str(ticket.owner_id or '') != str(form.owner.data) and ticket.author_id != current_user.id:
				Notification.send_notification(message='unassigned ticket', receiver_id=ticket.author_id, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
			if str(ticket.owner_id or '') != str(form.owner.data) and ticket.author_id == current_user.id:
				Notification.send_notification(message='unassigned ticket', receiver_id=ticket.owner_id, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
			ticket.owner_id = None
		else:
			if str(ticket.owner_id or '') != str(form.owner.data) and ticket.author_id != current_user.id:
				Notification.send_notification(message='assigned ticket', receiver_id=ticket.author_id, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
				Notification.send_notification(message='assigned ticket', receiver_id=form.owner.data, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
			if str(ticket.owner_id or '') != str(form.owner.data) and ticket.author_id == current_user.id:
				Notification.send_notification(message='assigned ticket', receiver_id=form.owner.data, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
			ticket.owner_id = form.owner.data
		
		if ticket.priority_id != int(form.priority.data) and ticket.author_id != current_user.id:
			Notification.send_notification(message='updated priority on ticket', receiver_id=ticket.author_id, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
		ticket.priority_id = form.priority.data

		if ticket.status_id != int(form.status.data) and ticket.author_id != current_user.id:
			Notification.send_notification(message='updated status on ticket', receiver_id=ticket.author_id, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
		ticket.status_id = form.status.data
		
		db.session.commit()
		flash('Ticket has been updated.', 'primary')
		return redirect(url_for('admin.view_ticket', id=id))
	return render_template('admin/view_ticket.html', form=form, comment_form=comment_form, ticket=ticket, comments=comments)

@admin_blueprint.route('/comment-ticket/<int:id>', methods=['GET', 'POST'])
@login_required(role='Administrator')
def comment_ticket(id):
	ticket_id = Ticket.query.get_or_404(id)
	comment_form = CommentForm()
	if comment_form.validate_on_submit():
		author_id = ticket_id.author_id
		owner_id = ticket_id.owner_id
		comment = comment_form.comment.data

		message = 'commented on ticket'
		# Send notification to the author and owner, if the ticket is not mine and is not assigned to me
		if author_id != current_user.id and owner_id != current_user.id and owner_id is not None:
			Notification.send_notification(message=message, receiver_id=author_id, sender_id=current_user.id, ticket_id=ticket_id.id, seen=False)
			Notification.send_notification(message=message, receiver_id=owner_id, sender_id=current_user.id, ticket_id=ticket_id.id, seen=False)
		# Send notification to the author, if the ticket is not mine
		elif author_id != current_user.id:
			Notification.send_notification(message=message, receiver_id=author_id, sender_id=current_user.id, ticket_id=ticket_id.id, seen=False)
		# Send notification to the owner, if the ticket is mine and is not assigned to me
		if author_id == current_user.id and owner_id != current_user.id and owner_id is not None:
			Notification.send_notification(message=message, receiver_id=owner_id, sender_id=current_user.id, ticket_id=ticket_id.id, seen=False)

		db.session.add(Comment(comment=comment, author_id=current_user.id, ticket_id=ticket_id.id))
		db.session.commit()
		flash('Your comment has been posted.', 'primary')
		return redirect(url_for('admin.view_ticket', id=id))
	return render_template('admin/view_ticket.html', comment_form=comment_form)

@admin_blueprint.route('/ticket/delete/<int:uid>/<int:tid>', methods=['GET', 'POST'])
@login_required(role='Administrator')
def delete_ticket(uid, tid):
	ticket_id = Ticket.query.get_or_404(tid)
	if request.method == 'POST':
		if ticket_id.file_link:
			FOLDER_ID = os.path.join(path, 'app/static/uploads/attachments/' + str(uid))
			os.remove(os.path.join(FOLDER_ID, ticket_id.file_link))

		db.session.delete(ticket_id)
		db.session.commit()
		flash('Ticket has been deleted.', 'primary')
		return redirect(url_for('admin.new_tickets'))
	return redirect(url_for('admin.view_ticket', id=tid))

@admin_blueprint.route('/download/attachment/<int:id>/<filename>')
def download_attachment(id, filename):
	FOLDER_ID = os.path.join(path, 'app/static/uploads/attachments/' + str(id))
	location = os.path.join(FOLDER_ID, filename)
	return send_file(location, as_attachment=True)

@admin_blueprint.route('/categories', methods=['GET', 'POST'])
@login_required(role='Administrator')
def category():
	categories = Category.query.all()
	form = CategoryForm()
	if form.validate_on_submit():
		category = Category(category=form.category.data)
		db.session.add(category)
		db.session.commit()
		flash('Category has been created.', 'primary')
		return redirect(url_for('admin.category'))
	return render_template('admin/category.html', form=form, categories=categories)

@admin_blueprint.route('/category/update/<int:id>', methods=['GET', 'POST'])
@login_required(role='Administrator')
def update_category(id):
	category_id = Category.query.get_or_404(id)
	form = CategoryForm()
	if form.validate_on_submit():
		category_id.category = form.category.data
		db.session.commit()
		flash('Category has been updated.', 'primary')
		return redirect(url_for('admin.category'))
	return render_template('admin/category.html', form=form)

@admin_blueprint.route('/category/delete/<int:id>', methods=['GET', 'POST'])
@login_required(role='Administrator')
def delete_category(id):
	category_id = Category.query.get_or_404(id)

app/templates/includes/alert.html
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/includes/footer.html
<div class="content-box mb-3 max-w-1000">
    <p class="text-center text-muted mb-0">
        Copyright &copy; {{ year }} &mdash; Tickette
    </p>
</div>

app/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg fixed-top navbar-lighten">
    <!-- Navbar Title -->
    <a class="navbar-brand navbar-link" href="javascript:void(0)">Tickette</a>

    <!-- Navbar Sidebar Menu Toggle -->
    <span class="navbar-text">
        <a href="javascript:void(0)" id="sidebar-toggle" class="navbar-bars">
            <i class="fa fa-bars" aria-hidden="true"></i>
        </a>
    </span>

    <!-- Navbar Dropdown Menu -->
    <div class="collapse navbar-collapse">
        <div class="dropdown dropdown-logged dropdown-logged-lighten">
            <a href="javascript:void(0)" data-toggle="dropdown" class="dropdown-logged-toggle dropdown-link">
                <span class="dropdown-user float-left">Menu</span>
            </a>
            <div class="dropdown-menu dropdown-logged-menu dropdown-menu-right border-0 dropdown-menu-lighten">
                <div class="dropdown-menu-arrow"></div>
                <a class="dropdown-item dropdown-logged-item" href="{% if current_user.role == 'Administrator' %} {{ url_for('admin.my_profile') }} {% elif current_user.role == 'Agent' %} {{ url_for('agent.my_profile') }} {% elif current_user.role == 'Customer' %} {{ url_for('customer.my_profile') }} {% endif %}"><i class="fa fa-user-o" aria-hidden="true"></i>Your profile</a>
                <a class="dropdown-item dropdown-logged-item" href="{% if current_user.role == 'Administrator' %} {{ url_for('admin.change_password') }} {% elif current_user.role == 'Agent' %} {{ url_for('agent.change_password') }} {% elif current_user.role == 'Customer' %} {{ url_for('customer.change_password') }} {% endif %}"><i class="fa fa-key" aria-hidden="true"></i>Change password</a>
                <div class="dropdown-divider border-light"></div>
                <a class="dropdown-item dropdown-logged-item" href="{{ url_for('auth.logout') }}"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a>
            </div>
        </div>
    </div>
</nav>

app/templates/includes/sidebar.html
<div class="sidebar sidebar-lighten">
    <!-- Sidebar Menu -->
    <div class="sidebar-menu">
        <!-- Menu -->
        <ul class="list list-unstyled list-scrollbar">
            <!-- Multi-level Dropdown Menu -->
            <li class="list-item">
                <p class="list-title text-uppercase">Dashboard</p>
                <ul class="list-unstyled">
                    <li><a href="{% if current_user.role == 'Administrator' %} {{ url_for('admin.dashboard') }} {% elif current_user.role == 'Agent' %} {{ url_for('agent.dashboard') }} {% elif current_user.role == 'Customer' %} {{ url_for('customer.dashboard') }} {% endif %}" class="list-link"><span class="list-icon"><i class="fa fa-home" aria-hidden="true"></i></span>Home</a></li>
                    <li><a href="javascript:void(0)" class="list-link link-arrow link-current"><span class="list-icon"><i class="fa fa-cog" aria-hidden="true"></i></span>Customer Support</a>
                        <ul class="list-unstyled list-hidden">
                            {% if current_user.role == 'Administrator' or current_user.role == 'Agent' %}
                            <li><a href="{% if current_user.role == 'Administrator' %} {{ url_for('admin.new_tickets') }} {% elif current_user.role == 'Agent' %} {{ url_for('agent.new_tickets') }} {% elif current_user.role == 'Customer' %} {{ url_for('customer.new_tickets') }} {% endif %}" class="list-link">New Tickets</a></li>
                            {% endif %}
                            <li><a href="{% if current_user.role == 'Administrator' %} {{ url_for('admin.my_tickets') }} {% elif current_user.role == 'Agent' %} {{ url_for('agent.my_tickets') }} {% elif current_user.role == 'Customer' %} {{ url_for('customer.my_tickets') }} {% endif %}" class="list-link">My Tickets</a></li>
                            {% if current_user.role == 'Administrator' or current_user.role == 'Agent' %}
                            <li><a href="javascript:void(0)" class="list-link link-arrow link-current">General</a>
                                <ul class="list-unstyled list-hidden">
                                    <li><a href="{% if current_user.role == 'Administrator' %} {{ url_for('admin.category') }} {% elif current_user.role == 'Agent' %} {{ url_for('agent.category') }} {% elif current_user.role == 'Customer' %} {{ url_for('customer.category') }} {% endif %}" class="list-link">Categories</a></li>
                                    <li><a href="{% if current_user.role == 'Administrator' %} {{ url_for('admin.priority') }} {% elif current_user.role == 'Agent' %} {{ url_for('agent.priority') }} {% elif current_user.role == 'Customer' %} {{ url_for('customer.priority') }} {% endif %}" class="list-link">Priorities</a></li>
                                    <li><a href="{% if current_user.role == 'Administrator' %} {{ url_for('admin.status') }} {% elif current_user.role == 'Agent' %} {{ url_for('agent.status') }} {% elif current_user.role == 'Customer' %} {{ url_for('customer.status') }} {% endif %}" class="list-link">Statuses</a></li>
                                </ul>
                            </li>
                            {% endif %}
                        </ul>
                    </li>
                    <!-- Notifications -->
                    <li>
                        <a href="{% if current_user.role == 'Administrator' %} {{ url_for('admin.notifications') }} {% elif current_user.role == 'Agent' %} {{ url_for('agent.notifications') }} {% elif current_user.role == 'Customer' %} {{ url_for('customer.notifications') }} {% endif %}" class="list-link clearfix">
                            <div class="float-left">
                                <span class="list-icon">
                                    <i class="fa fa-bell" aria-hidden="true"></i>
                                </span>Notifications
                            </div>
                            <div class="float-right">
                                <span class="badge badge-pill badge-secondary">{{ notifications|length }}</span>
                            </div>
                        </a>
                    </li>
                </ul>
            </li>

            <!-- Simple Menu -->
            {% if current_user.role == 'Administrator' %}
            <li class="list-item">
                <p class="list-title text-uppercase">User Management</p>
                <ul class="list-unstyled">
                    <li><a href="{{ url_for('admin.create_account') }}" class="list-link"><span class="list-icon"><i class="fa fa-user" aria-hidden="true"></i></span>Create an account</a></li>
                </ul>
            </li>
            {% endif %}
        </ul>
    </div>
</div>