app/agent/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed

from wtforms import StringField, PasswordField, SelectField, TextAreaField
from wtforms.validators import DataRequired, Length, EqualTo

from app.models import User, Category, Priority, Status

from sqlalchemy import or_

allowed_exts = ['pdf', 'docx', 'png', 'jpg', 'jpeg', 'gif']

class TicketForm(FlaskForm):
	subject = StringField('Subject',
		validators=[DataRequired(), Length(min=4, max=128)])
	category = SelectField('Category',
		validators=[DataRequired()])
	body = TextAreaField('Message',
		validators=[DataRequired()])
	attachment = FileField('Attachment',
		validators=[FileAllowed(allowed_exts, 'This file extension is not allowed')])

	def __init__(self, *args, **kwargs):
		super(TicketForm, self).__init__(*args, **kwargs)
		self.category.choices = [('', '-- Please select category --')]+[(category.id, category.category) for category in Category.query.all()]

class UpdateTicketForm(FlaskForm):
	priority = SelectField('Priority',
		validators=[DataRequired()])
	status = SelectField('Status',
		validators=[DataRequired()])
	owner = SelectField('Assignee')

	def __init__(self, *args, **kwargs):
		super(UpdateTicketForm, self).__init__(*args, **kwargs)
		self.owner.choices = [('', '-- Choose an assignee --')]+[(owner.id, owner.name)
			for owner in User.query.filter(or_(User.role=='Administrator', User.role=='Agent')).all()]
		self.priority.choices = [('', '-- Please select priority --')]+[(priority.id, priority.priority)
			for priority in Priority.query.all()]
		self.status.choices = [('', '-- Please select status --')]+[(status.id, status.status)
			for status in Status.query.all()]

class CategoryForm(FlaskForm):
	category = StringField('Category',
		validators=[DataRequired(), Length(min=4, max=64)])

class PriorityForm(FlaskForm):
	priority = StringField('Priority',
		validators=[DataRequired(), Length(min=4, max=32)])

class CommentForm(FlaskForm):
	comment = TextAreaField('Comment',
		validators=[DataRequired()])

class ChangeProfileForm(FlaskForm):
	profile = FileField('Change Profile',
		validators=[FileRequired(), FileAllowed(['png', 'jpg', 'jpeg'], 'This file extension is not allowed')])

class ChangePasswordForm(FlaskForm):
	password = PasswordField('New Password',
		validators=[DataRequired(), Length(min=6, max=32)])
	confirm_password = PasswordField('Confirm Password',
		validators=[DataRequired(), EqualTo('password')])

app/agent/views.py
from flask import Blueprint, current_app, render_template as _render, send_file, redirect, request, url_for, flash
from flask_login import current_user

from app.agent.forms import TicketForm, UpdateTicketForm, CommentForm, CategoryForm, PriorityForm, ChangeProfileForm, ChangePasswordForm
from app.models import User, Ticket, Category, Priority, Status, Comment, Notification

from app.utils.generate_digits import random_numbers
from app.utils.authorized_role import login_required
from app.exts import db

from werkzeug.utils import secure_filename

from sqlalchemy import desc
from sqlalchemy import or_

from werkzeug.security import generate_password_hash

import datetime
import uuid
import os

agent_blueprint = Blueprint('agent', __name__)
path = os.getcwd()

# Pass variable to all templates
def render_template(*args, **kwargs):
	notifications = Notification.query.filter(Notification.receiver_id==current_user.id).filter(Notification.seen==False).order_by(desc(Notification.created_at)).all()
	year = datetime.date.today().year
	return _render(*args, **kwargs, notifications=notifications, year=year)

@agent_blueprint.route('/dashboard')
@login_required(role='Agent')
def dashboard():
	id = current_user.id
	open = Ticket.query.filter(or_(Ticket.author_id==id, Ticket.owner_id==id)).filter_by(status_id=1).all()
	solved = Ticket.query.filter(or_(Ticket.author_id==id, Ticket.owner_id==id)).filter_by(status_id=2).all()
	pending = Ticket.query.filter(or_(Ticket.author_id==id, Ticket.owner_id==id)).filter_by(status_id=3).all()
	closed = Ticket.query.filter(or_(Ticket.author_id==id, Ticket.owner_id==id)).filter_by(status_id=4).all()
	
	return render_template('agent/dashboard.html', open=open, solved=solved, pending=pending, closed=closed)

@agent_blueprint.route('/my-tickets', methods=['GET'])
@login_required(role='Agent')
def my_tickets():
	tickets = Ticket.query.filter(or_(Ticket.author_id==current_user.id, Ticket.owner_id==current_user.id)).order_by(desc(Ticket.created_at)).all()
	form = TicketForm()
	return render_template('agent/my_tickets.html', form=form, tickets=tickets)

@agent_blueprint.route('/new-tickets', methods=['GET'])
@login_required(role='Agent')
def new_tickets():
	tickets = Ticket.query.order_by(desc(Ticket.created_at)).all()
	form = TicketForm()
	return render_template('agent/new_tickets.html', form=form, tickets=tickets)

@agent_blueprint.route('/create-ticket', methods=['GET', 'POST'])
@login_required(role='Agent')
def create_ticket():
	form = TicketForm()
	if form.validate_on_submit():
		number = random_numbers()
		priority = 1 # Low priority
		status = 1 # Open status

		id = current_user.id
		file = form.attachment.data
		if file is not None:
			FOLDER_ID = os.path.join(path, 'app/static/uploads/attachments/' + str(id))
			# Recursively create the paths, if the preceding path doesn't exist
			if not os.path.exists(FOLDER_ID):
				os.makedirs(FOLDER_ID)

			original_f = file.filename
			# Rename the uploaded file
			filename, ext = os.path.splitext(original_f)
			filename = uuid.uuid4().hex
			attachment = secure_filename(str(filename + ext))
			# then save it to the designated folder
			file.save(os.path.join(FOLDER_ID, attachment))
		else:
			attachment = None
			original_f = None

		ticket = Ticket(number=number, subject=form.subject.data, body=form.body.data, author_id=current_user.id, owner_id=None, category_id=int(form.category.data), priority_id=priority, status_id=status, orig_file=original_f, file_link=attachment)
		
		db.session.add(ticket)
		db.session.commit()
		flash('Ticket has been created.', 'primary')
		return redirect(url_for('agent.new_tickets'))

@agent_blueprint.route('/view-ticket/<int:id>', methods=['GET', 'POST'])
@login_required(role='Agent')
def view_ticket(id):
	ticket = Ticket.query.filter_by(id=id).first()
	comments = Comment.query.filter(Comment.ticket_id==id).all()
	
	if not ticket:
		return redirect(url_for('agent.new_tickets'))
	
	form = UpdateTicketForm(owner=ticket.owner_id, priority=ticket.priority_id, status=ticket.status_id)
	comment_form = CommentForm()
	if form.validate_on_submit():
		if not form.owner.data:
			if str(ticket.owner_id or '') != str(form.owner.data) and ticket.author_id != current_user.id:
				Notification.send_notification(message='unassigned ticket', receiver_id=ticket.author_id, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
			if str(ticket.owner_id or '') != str(form.owner.data) and ticket.author_id == current_user.id:
				Notification.send_notification(message='unassigned ticket', receiver_id=ticket.owner_id, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
			ticket.owner_id = None
		else:
			if str(ticket.owner_id or '') != str(form.owner.data) and ticket.author_id != current_user.id:
				Notification.send_notification(message='assigned ticket', receiver_id=ticket.author_id, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
				Notification.send_notification(message='assigned ticket', receiver_id=form.owner.data, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
			if str(ticket.owner_id or '') != str(form.owner.data) and ticket.author_id == current_user.id:
				Notification.send_notification(message='assigned ticket', receiver_id=form.owner.data, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
			ticket.owner_id = form.owner.data
		
		if ticket.priority_id != int(form.priority.data) and ticket.author_id != current_user.id:
			Notification.send_notification(message='updated priority on ticket', receiver_id=ticket.author_id, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
		ticket.priority_id = form.priority.data

		if ticket.status_id != int(form.status.data) and ticket.author_id != current_user.id:
			Notification.send_notification(message='updated status on ticket', receiver_id=ticket.author_id, sender_id=current_user.id, ticket_id=ticket.id, seen=False)
		ticket.status_id = form.status.data
		
		db.session.commit()
		flash('Ticket has been updated.', 'primary')
		return redirect(url_for('agent.view_ticket', id=id))
	return render_template('agent/view_ticket.html', form=form, comment_form=comment_form, ticket=ticket, comments=comments)

@agent_blueprint.route('/comment-ticket/<int:id>', methods=['GET', 'POST'])
@login_required(role='Agent')
def comment_ticket(id):
	ticket_id = Ticket.query.get_or_404(id)
	comment_form = CommentForm()
	if comment_form.validate_on_submit():
		author_id = ticket_id.author_id
		owner_id = ticket_id.owner_id
		comment = comment_form.comment.data

		message = 'commented on ticket'
		# Send notification to the author and owner, if the ticket is not mine and is not assigned to me
		if author_id != current_user.id and owner_id != current_user.id and owner_id is not None:
			Notification.send_notification(message=message, receiver_id=author_id, sender_id=current_user.id, ticket_id=ticket_id.id, seen=False)
			Notification.send_notification(message=message, receiver_id=owner_id, sender_id=current_user.id, ticket_id=ticket_id.id, seen=False)
		# Send notification to the author, if the ticket is not mine
		elif author_id != current_user.id:
			Notification.send_notification(message=message, receiver_id=author_id, sender_id=current_user.id, ticket_id=ticket_id.id, seen=False)
		# Send notification to the owner, if the ticket is mine and is not assigned to me
		if author_id == current_user.id and owner_id != current_user.id and owner_id is not None:
			Notification.send_notification(message=message, receiver_id=owner_id, sender_id=current_user.id, ticket_id=ticket_id.id, seen=False)

		db.session.add(Comment(comment=comment, author_id=current_user.id, ticket_id=ticket_id.id))
		db.session.commit()
		flash('Your comment has been posted.', 'primary')
		return redirect(url_for('agent.view_ticket', id=id))
	return render_template('agent/view_ticket.html', comment_form=comment_form)

@agent_blueprint.route('/ticket/delete/<int:uid>/<int:tid>', methods=['GET', 'POST'])
@login_required(role='Agent')
def delete_ticket(uid, tid):
	ticket_id = Ticket.query.get_or_404(tid)
	if request.method == 'POST':
		if ticket_id.file_link:
			FOLDER_ID = os.path.join(path, 'app/static/uploads/attachments/' + str(uid))
			os.remove(os.path.join(FOLDER_ID, ticket_id.file_link))

		db.session.delete(ticket_id)
		db.session.commit()
		flash('Ticket has been deleted.', 'primary')
		return redirect(url_for('agent.new_tickets'))
	return redirect(url_for('agent.view_ticket', id=tid))

@agent_blueprint.route('/download/attachment/<int:id>/<filename>')
def download_attachment(id, filename):
	FOLDER_ID = os.path.join(path, 'app/static/uploads/attachments/' + str(id))
	location = os.path.join(FOLDER_ID, filename)
	return send_file(location, as_attachment=True)

@agent_blueprint.route('/categories', methods=['GET', 'POST'])
@login_required(role='Agent')
def category():
	categories = Category.query.all()
	form = CategoryForm()
	if form.validate_on_submit():
		category = Category(category=form.category.data)
		db.session.add(category)
		db.session.commit()
		flash('Category has been created.', 'primary')
		return redirect(url_for('agent.category'))
	return render_template('agent/category.html', form=form, categories=categories)

@agent_blueprint.route('/category/update/<int:id>', methods=['GET', 'POST'])
@login_required(role='Agent')
def update_category(id):
	category_id = Category.query.get_or_404(id)
	form = CategoryForm()
	if form.validate_on_submit():
		category_id.category = form.category.data
		db.session.commit()
		flash('Category has been updated.', 'primary')
		return redirect(url_for('agent.category'))
	return render_template('agent/category.html', form=form)

@agent_blueprint.route('/category/delete/<int:id>', methods=['GET', 'POST'])
@login_required(role='Agent')
def delete_category(id):
	category_id = Category.query.get_or_404(id)
	if request.method == 'POST':
		db.session.delete(category_id)
		db.session.commit()
		flash('Category has been deleted.', 'primary')

app/templates/agent/category.html
{% from 'macros/render_input.html' import render_input %}

{% extends 'layouts/dashboard.base.html' %}
{% block style %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/datatables/css/datatables.bootstrap4.min.css') }}">
{% endblock %}

{% block header %}
    {% block title %}Categories{% endblock %}
{% endblock %}
{% block text %}
    Create new category for your tickets.
{% endblock %}

{% block button %}
    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#createModal">
        Create New
    </button>
{% endblock %}
{% block content %}

<div class="max-w-1000">
    {% include 'includes/alert.html' %}
</div>

<!-- Category Table -->
<div class="content-box mb-3 content-lighten max-w-1000">
    <table id="categoryTable" class="table table-striped table-borderless table-responsive-sm">
        <thead>
            <tr>
                <th>#</th>
                <th>Category</th>
                <th>Date Created</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for row in categories %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row.category }}</td>
                <td>{{ row.created_at.strftime('%m-%d-%Y, %H:%M') }}</td>
                <td>
                    <button class="btn btn-primary btn-sm"
                        {% if row.id == 1 %}
                            disabled
                        {% else %}
                            data-toggle="modal" data-target="#updateModal{{ row.id }}"
                        {% endif %}>
                        <i class="fa fa-edit"></i>
                    </button>
                    <button class="btn btn-danger btn-sm"
                        {% if row.id == 1 %}
                            disabled
                        {% else %}
                            data-toggle="modal" data-target="#deleteModal{{ row.id }}"
                        {% endif %}>
                        <i class="fa fa-trash"></i>
                    </button>
                </td>
            </tr>
            <!-- Update Modal -->
            <div class="modal fade" id="updateModal{{ row.id }}" tabindex="-1" aria-labelledby="updateModalLabel{{ row.id }}" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="updateModalLabel{{ row.id }}">Update Category</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form action="{{ url_for('agent.update_category', id=row.id) }}" method="POST">
                                {{ form.csrf_token }}
                                <div class="form-group">
                                    {{ render_input(form.category, "Category", "Category is required", value=row.category) }}
                                </div>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Delete Modal -->
            <div class="modal fade" id="deleteModal{{ row.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ row.id }}" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel{{ row.id }}">Delete Confirmation</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Are you sure you want to delete this category? This action cannot be undone.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <form action="{{ url_for('agent.delete_category', id=row.id) }}" method="POST">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <input type="submit" class="btn btn-danger" value="Delete">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Create Modal -->
<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createModalLabel">Create New</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('agent.category') }}" method="POST">
                    {{ form.csrf_token }}
                    <div class="form-group">
                        {{ render_input(form.category, "Category", "Category is required") }}
                    </div>
                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='vendor/datatables/js/jquery.datatables.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/datatables/js/datatables.bootstrap4.min.js') }}"></script>
<script>
    $(document).ready(function() {
        $('#categoryTable').DataTable({'ordering': false});
    });
</script>
{% endblock %}

app/templates/agent/change_password.html
{% from 'macros/render_input.html' import render_input %}

{% extends 'layouts/dashboard.base.html' %}
{% block header %}
    {% block title %}Change Password{% endblock %}
{% endblock %}
{% block text %}
    Make sure your password is strong and easy to remember.
{% endblock %}
{% block content %}

<div class="max-w-1000">
    {% include 'includes/alert.html' %}
</div>

<!-- Change Password Form -->
<div class="content-box mb-3 content-lighten max-w-1000">
    <form action="#" method="POST" class="form-validation max-w-800" novalidate="">
        {{ form.csrf_token }}
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="password">New Password</label>
                    {{ render_input(form.password, "", "Password must be 6 to 32 characters long", **{"data-eye": ""}) }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="confirm_password">Confirm Password</label>
                    {{ render_input(form.confirm_password, "", "Confirm password is required", **{"data-eye": ""}) }}
                </div>
            </div>
        </div>
        <button type="submit" id="submit" class="btn btn-primary">Change Password</button>
    </form>
</div>

{% endblock %}
{% block script %}
{{ super() }}
<!--
<script>
    $('#submit').click(function(e) {
        e.preventDefault();
        alert('This functionality is not available for the demo.');
    });
</script>
-->
{% endblock %}

app/templates/agent/dashboard.html
{% extends 'layouts/dashboard.base.html' %}
{% block header %}
    {% block title %}Dashboard{% endblock %}
{% endblock %}
{% block content %}

<div class="max-w-1000">
    <div class="row">
        <div class="col-md-4 col-xl-3">
            <div class="card bg-clr-blue order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Open</h6>
                    <h2 class="text-right">
                        <i class="fa fa-envelope-open f-left"></i>
                        <span>{{ open|length }}</span>
                    </h2>
                    <p class="m-b-0">Total open tickets</p>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-xl-3">
            <div class="card bg-clr-green order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Solved</h6>
                    <h2 class="text-right">
                        <i class="fa fa-thumbs-up f-left"></i>
                        <span>{{ solved|length }}</span>
                    </h2>
                    <p class="m-b-0">Total solved tickets</p>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-xl-3">
            <div class="card bg-clr-yellow order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Pending</h6>
                    <h2 class="text-right">
                        <i class="fa fa-hourglass-end f-left"></i>
                        <span>{{ pending|length }}</span>
                    </h2>
                    <p class="m-b-0">Total pending tickets</p>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-xl-3">
            <div class="card bg-clr-pink order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Closed</h6>
                    <h2 class="text-right">
                        <i class="fa fa-envelope f-left"></i>
                        <span>{{ closed|length }}</span>
                    </h2>
                    <p class="m-b-0">Total closed tickets</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/agent/status.html
{% extends 'layouts/dashboard.base.html' %}
{% block header %}
    {% block title %}Statuses{% endblock %}
{% endblock %}
{% block content %}

<!-- Status Table -->
<div class="content-box mb-3 content-lighten max-w-1000">
    <table id="statusTable" class="table table-striped table-borderless">
        <thead>
            <tr>
                <th>#</th>
                <th>Status</th>
                <th>Date Created</th>
            </tr>
        </thead>
        <tbody>
            {% for row in statuses %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row.status }}</td>
                <td>{{ row.created_at.strftime('%m-%d-%Y, %H:%M') }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

app/templates/agent/view_ticket.html
{% from 'macros/render_input.html' import render_input %}
{% from 'macros/render_select.html' import render_select %}

{% extends 'layouts/dashboard.base.html' %}
{% block style %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/froala-editor/css/froala_editor.pkgd.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/froala-editor/css/froala_style.min.css') }}">
{% endblock %}

{% block header %}
    {% block title %}Ticket Information{% endblock %}
{% endblock %}
{% block text %}
    Leave a comment, update, delete, or assign this ticket.
{% endblock %}

{% block button %}
    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal">
        Delete
    </button>
{% endblock %}
{% block content %}

<div class="max-w-1000">
    {% include 'includes/alert.html' %}
</div>

<!-- Ticket Info -->
<div class="content-box mb-3 content-lighten max-w-1000">
    <table class="table table-striped table-borderless">
        <tbody>
            <form action="{{ url_for('agent.view_ticket', id=ticket.id) }}" method="POST">
                {{ form.csrf_token }}
                <tr>
                    <td>Date Created</td>
                    <td>{{ ticket.created_at.strftime('%d %b %Y, %H:%M %p') }}</td>
                </tr>
                <tr>
                    <td class="w-25">Number</td>
                    <td>{{ ticket.number }}</td>
                </tr>
                <tr>
                    <td>Author</td>
                    <td>{{ ticket.author.name }}</td>
                </tr>
                <tr>
                    <td>E-mail address</td>
                    <td>
                        <a href="mailto:{{ ticket.author.email }}">{{ ticket.author.email }}</a>
                    </td>
                </tr>
                <tr>
                    <td>Subject</td>
                    <td>{{ ticket.subject }}</td>
                </tr>
                <tr>
                    <td>Body</td>
                    <td>
                        <div class="fr-view">{{ ticket.body|safe }}</div>
                    </td>
                </tr>
                <tr>
                    <td>Assignee</td>
                    <td>
                        <div class="form-group row">
                            <div class="col-md-5">
                                {{ render_select(form.owner, "Assignee is required") }}
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Category</td>
                    <td>{{ ticket.category.category }}</td>
                </tr>
                <tr>
                    <td>Priority</td>
                    <td>
                        <div class="form-group row">
                            <div class="col-md-5">
                                {{ render_select(form.priority, "Priority is required") }}
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Status</td>
                    <td>
                        <div class="form-group row">
                            <div class="col-md-5">
                                {{ render_select(form.status, "Status is required") }}
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Attachment</td>
                    <td>
                        {% if ticket.file_link %}
                        <a href="{{ url_for('agent.download_attachment', id=ticket.author.id, filename=ticket.file_link) }}">
                            {{ ticket.orig_file }}
                        </a>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <button type="submit" class="btn btn-primary btn-sm">Update</button>
                        <a href="{{ url_for('agent.new_tickets') }}" class="btn btn-secondary btn-sm">
                            Back
                        </a>
                    </td>
                </tr>
            </form>
        </tbody>
    </table>
</div>

<!-- Comment Section -->
<div class="content-box mb-3 content-lighten max-w-1000">
    <div class="comment-wrapper">
        {% if ticket.status.status != 'Closed' %}
        <form action="{{ url_for('agent.comment_ticket', id=ticket.id) }}" method="POST">
            {{ comment_form.csrf_token }}
            <div class="form-group">
                {{ render_input(comment_form.comment, "Write a message...", "Message is required", rows="5") }}
            </div>
            <button type="submit" class="btn btn-primary btn-sm pull-right">Post</button>
        </form>
        {% else %}
        <div class="text-center">
            <p>This ticket has been closed.</p>
        </div>
        {% endif %}
        
        <div class="clearfix"></div>
        <hr>
        
        {% for comment in comments %}
        <ul class="media-list">
            <li class="media">
                <a href="javascript:void(0)" class="pull-left mt-3 mr-3">
                    <img src="{{ url_for('static', filename='uploads/profiles/' + comment.user.image) }}" alt="profile-img" class="rounded">
                </a>
                <div class="media-body">
                    <span class="text-muted pull-right">
                        <small class="text-muted">{{ comment.created_at.strftime('%d %b %Y, %H:%M %p') }}</small>
                    </span>
                    <strong class="text-dark">{{ comment.user.name }}</strong>
                    <small class="text-muted">{{ comment.user.role }}</small>
                    <p>
                        <div class="fr-view">{{ comment.comment|safe }}</div>
                    </p>
                </div>
            </li>
        </ul>
        {% endfor %}
    </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this ticket? This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('agent.delete_ticket', uid=ticket.author.id, tid=ticket.id) }}" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <input type="submit" class="btn btn-danger" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='vendor/froala-editor/js/froala_editor.pkgd.min.js') }}"></script>
<script>
    $(document).ready(function() {
        new FroalaEditor('textarea#comment', {
            toolbarButtons: ['fontFamily', '|', 'bold', 'italic', 'underline', 'undo', 'redo', 'codeView'],
            fontFamilySelection: true,
            pluginsEnabled: ['fontFamily']
        });
    });
</script>
{% endblock %}